steps:
  # Step 1: The 5 Minute Wait
  - name: 'ubuntu'
    args: ['sleep', '300']
    id: 'waiting-phase'

  # Step 2: Install Dependencies & Run Script
  - name: 'python:3.9'
    # --- FIX IS HERE: Point to the correct nested folder ---
    dir: 'annotation-project/annotation-pipeline' 
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Installing FFmpeg..."
        apt-get update && apt-get install -y ffmpeg
        
        echo "Installing Python Requirements..."
        pip install -r requirements.txt
        
        echo "Running Script..."
        python3 annotations.py
    env:
      - 'S3_KEY=${_FILE_NAME}'
      - 'GCS_BUCKET=${_BUCKET_NAME}'

# Step 3: Save Artifacts
artifacts:
  objects:
    location: 'gs://annotation-output-bucket/results/${_FILE_NAME}/'
    paths: 
      # --- ARTIFACT PATHS ALSO UPDATED ---
      - 'annotation-project/annotation-pipeline/frames/*'
      - 'annotation-project/annotation-pipeline/predict/*'
      - 'annotation-project/annotation-pipeline/inspection.csv'

options:
  logging: CLOUD_LOGGING_ONLY
